[package]
name = "jmatt_invoice"
version = "0.4.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
printpdf = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prettytable-rs = "0.10.0"


eframe = "0.28"
egui = "0.28"
rfd = "0.14"
